[package]
name = "win_etw_provider"
version = "0.1.0"
authors = ["Arlie Davis <ardavis@microsoft.com>"]
edition = "2018"
description = "Enables apps to report events to Event Tracing for Windows (ETW)."
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/sivadeilra/win_etw"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
widestring = "^0.4"
zerocopy = "^0.3"
win_etw_macros = { path = "../win_etw_macros" }
win_etw_metadata = { path = "../win_etw_metadata" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "^0.3", features = ["evntprov", "winerror", "evntrace"] }
w32-error = "^1.0"

[dev-dependencies]
atomic_lazy = { git = "https://github.com/sivadeilra/atomic_lazy" }

[features]
std = []
default = ["std"]
# dev is used only for development
dev = []